# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29e40aa935f864613ed630c91dc5577bb8a2458b9e379f0a3c266e53612d1148538064ab3025e2b311e244f12ca1256c93573caf68fe1cbdee2561bfcadb4680

test:
  secret_key_base: e10ef8b0e113bfa57d5e8312f4c99812f13a199b7848c43a6398c546fe2d9e152682b4ce805ca7ba20f5f31c20396817b940ecd29c7fe91deef6f396057f483d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
